main: com.cavetale.kotl.KOTLPlugin
name: KingOfTheLadder
version: '0.1'
api-version: '1.17'
description: King of the Ladder Event
author: StarTux
website: https://github.com/StarTux/KingOfTheLadder
depend: [WorldEdit, Sidebar]
softdepend: []
commands:
  kotl:
    description: King of the Ladder Warp
    permission: kotl.kotl
    usage: /kotl
  kotla:
    description: King of the Ladder Admin interface
    permission: kotl.admin
    usage: |-
      /kotl
      /kotla reload - Reload game
      /kotla save - Save game - Should not be needed
      /kotla setstate PAUSE|CLIMB
      /kotla setarea - Set area
      /kotla setgoal - Set goal block under feet
      /kotla setgoalmaterial <mat> - Set goal material
      /kotla addspawn - Add spawn block under feet
      /kotla clearspawn - Clear spawn blocks
      /kotla clearwinners - Clear winners
      /kotla setlevel <name> <lvl> - Set player level
      /kotla clearlevels - Clear player levels
permissions:
  kotl.kotl:
    description: Use /kotl
