main: com.cavetale.kotl.KOTLPlugin
name: KingOfTheLadder

version: 0.1
api-version: 1.19

description: King of the Ladder Event
author: StarTux
website: https://github.com/StarTux/KingOfTheLadder

depend: [Core, WorldEdit, Sidebar, Mytems, Fam]
softdepend: []

commands:

  kotl:
    description: King of the Ladder Warp
    permission: kotl.kotl
    usage: /kotl

  kotla:
    description: King of the Ladder Admin interface
    permission: kotl.admin
    usage: /kotla

permissions:

  kotl.kotl:
    description: Use /kotl
    default: op

  kotl.admin:
    description: Use /kotla
    default: op